### ISSUE TITLE
I use RxFFmpegPlayerView play video , but it only has voice , no picture .

### ISSUE THREAD

**Issue by siyrs** [nor0x/XDroidFFmpeg#9]
i has do much test . 
i think it some error in the so lib ,please fix this .
Thanks very much

**Comment by siyrs** [comment]
my device is Android 10 .

**Comment by nor0x** [comment]
do you have a repro project i can take a look at?

**Comment by siyrs** [comment]
Thanks for your reply .
i push the code to the github .
it build by AS , just demo .
i replace more SurfaceView to try play , but all failed .


[https://github.com/whwei2008/ffmpeg](url)

**Comment by nor0x** [comment]
thanks for the repro. i would suggest you post this issue in the main repository over at https://github.com/microshow/RxFFmpeg this is where the main code is maintained. This repository is for the **Xamarin.Android** bindings

**Comment by siyrs** [comment]
thanks . i pull the main code and try it .
